apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-proxy-windows
  labels:
    k8s-app: kube-proxy-windows
    {{- include "kube-proxy.labels" . | nindent 4 }}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy-windows
      {{- include "kube-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        k8s-app: kube-proxy-windows
        {{- include "kube-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: kube-proxy
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "{{ .Values.securityContext.runAsUserName }}"
      hostNetwork: true
      initContainers:
      - name: setup-source-vip
        image: {{ .Values.sourcevipImage.repository }}:{{ .Values.sourcevipImage.tag }}
        imagePullPolicy: {{ .Values.sourcevipImage.pullPolicy }}
        command: ["/source-vip"]
        volumeMounts:
        - name: source-vip
          mountPath: "/source-vip"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          - --hostname-override=$(NODE_NAME)
          - --config=/var/lib/kube-proxy/kubeconfig.conf
          - --v=4
          - --proxy-mode=kernelspace
          - --feature-gates=WinOverlay=true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
          - mountPath: /var/lib/kube-proxy
            name: kube-proxy
          - name: source-vip
            mountPath: "/source-vip"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        kubernetes.io/os: windows
        {{- with .Values.nodeSelector }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
        {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - configMap:
          name: kube-proxy
        name: kube-proxy
      - name: source-vip
        emptyDir: {}
  updateStrategy:
    type: RollingUpdate